# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

empTraceVariogram <- function(Coords, Fs, Lags, Directions, distTolerance, Step = 0, angTolerance = 0, isPartial = FALSE) {
    .Call('_fdagstat_empTraceVariogram', PACKAGE = 'fdagstat', Coords, Fs, Lags, Directions, distTolerance, Step, angTolerance, isPartial)
}

empTraceCrossVariogram <- function(Coords, Fs, SFs, Lags, Directions, distTolerance, Step = 0, angTolerance = 0) {
    .Call('_fdagstat_empTraceCrossVariogram', PACKAGE = 'fdagstat', Coords, Fs, SFs, Lags, Directions, distTolerance, Step, angTolerance)
}

isoCoordinates <- function(CoordsF1, CoordsF2) {
    .Call('_fdagstat_isoCoordinates', PACKAGE = 'fdagstat', CoordsF1, CoordsF2)
}

empTracePseudoCrossVariogram <- function(primaryCoords, Fs, secondaryCoords, SFs, Lags, Directions, distTolerance, Step = 0, angTolerance = 0) {
    .Call('_fdagstat_empTracePseudoCrossVariogram', PACKAGE = 'fdagstat', primaryCoords, Fs, secondaryCoords, SFs, Lags, Directions, distTolerance, Step, angTolerance)
}

